### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by justinddaniel** [learn-co-curriculum/cli-data-gem-assessment#31]
_Build your application. This is going to be different from labs you have done on Learn. Do not click Open IDE and create your application within the lesson files. Instead:

Watch this video on how to create and continue your project in the IDE In Browser
Use this IDE Sandbox. Do not close the Sandbox without completing the next step or your work will be lost._

In the link above for IDE Sandbox, it is a broken link that simply takes you back to the page with a message that you do not have access permission. This has happened on both my account and a student's account, so it is not specific to one student.

**Comment by cjbrock** [comment]
Hey @justinddaniel! I believe the reason that the link points to that particular lesson is because if you look at the top right corner, there is a link to the IDE sandbox on that lesson page. It's not super intuitive, however. I  have asked engineering if there is a way to directly link to the sandbox so that it's not super confusing for our instructors and students, and I'll let you know as soon as I know. In the meantime, feel free to use that button. 

//<3 Corinna
<img width="1061" alt="screen shot 2018-12-10 at 12 36 33 pm" src="https://user-images.githubusercontent.com/162531/49750252-64125c00-fc78-11e8-8f5a-d01079ca9d21.png">
