### ISSUE TITLE
Banner incorrectly state my project review is unscheduled

### ISSUE THREAD

**Issue by kristenkinnearohlmann** [learn-co-curriculum/cli-data-gem-assessment#40]
I have scheduled the review for my CLI Data Gem project for Wed, Mar 3 2021 but the banner within Learn.co displays that I have not scheduled. I have received emails with the link to meet with a reviewer but the banner continues to display.

**Comment by graciemcguire** [comment]
Thanks for raising this issue. Based on your description, it sounds like the issue may be related to your Learn setup rather than with the lesson itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

Please re-open this issue if you believe the lesson needs to be updated.

Hope you are/were able to get this resolved!
